name: Enviar Santoral Push

on:
  schedule:
    # 06:05 UTC equivale a las 08:05 AM hora peninsular española (UTC+2 en verano)
    - cron: '5 6 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run:  pip install requests beautifulsoup4

      - name: Ejecutar script
        env:
          TOPIC_NTFY: 'santoral-diario-2026'
        run: python bot.py
        
